app/Frontend/__init__.py
"""
Code permettant de définir l'accès aux routes concernant les fonctions utilisateurs du blog.
"""

from flask import Blueprint

frontend_bp = Blueprint('frontend', __name__,)

from app.Frontend import routes

app/Frontend/routes.py
"""
Code permettant de définir les routes concernant les fonctions des utilisateurs du blog au niveau du frontend.
"""
import os

from app.Frontend import frontend_bp

from flask import abort

from app.Models.forms import NewSubjectForumForm, CommentSubjectForm, CommentVideoForm

from app.Models.subject_forum import SubjectForum
from app.Models.comment_subject import CommentSubject

from app.Models.videos import Video

from app.Models.comment_video import CommentVideo

from flask import render_template, request

from app.utils_videos import get_videos_from_db, archived_videos, popular_videos

YOUTUBE_API = os.getenv('YOUTUBE_API')
ID_CHANNEL = os.getenv('ID_CHANNEL')

from dotenv import load_dotenv

load_dotenv()


# Route permettant d'accéder au forum du blog.
@frontend_bp.route('/acces-forum')
def forum():
    """
    Route permettant d'accéder à la page du forum du blog.

    Returns:
        Template HTML 'frontend/forum.html' affichant la page du forum et ses sujets.
    """
    # Instanciation du formulaire.
    formsubjectforum = NewSubjectForumForm()

    # Récupération de tous les sujets de la table de données.
    subjects = SubjectForum.query.all()


    return render_template('frontend/forum.html', formsubjectforum=formsubjectforum, subjects=subjects)


# Route pour visualiser le sujet de discussion sur un sujet en particulier.
@frontend_bp.route('/acces-sujet-forum/<int:subject_id>', methods=['GET', 'POST'])
def forum_subject(subject_id):
    """
    Route permettant d'accéder à un sujet spécifique du forum.

    Args:
        subject_id (int) : L'identifiant du sujet à afficher.

    Returns :
        Template HTML 'frontend/subject_forum.html' avec les détails du sujet et ses commentaires associés.

    Raises :
        404 Error : Si aucun sujet correspondant à l'ID spécifié n'est trouvé dans la base de données.
    """
    # Création de l'instance des formulaires.
    formcomment = CommentSubjectForm()

    # Récupération du sujet spécifié par l'id depuis la base de données.
    subject = SubjectForum.query.get_or_404(subject_id)

    # Vérification de l'existence du sujet.
    if not subject:
        # Si le sujet n'existe pas, erreur 404 renvoyée.
        abort(404)

    # Récupération des commentaires associés à ce sujet.
    comment_subject = CommentSubject.query.filter_by(subject_id=subject_id).all()

    return render_template("frontend/subject_forum.html", subject=subject, subject_id=subject_id,
                           comment_subject=comment_subject, formcomment=formcomment)


# Route permettant d'afficher toutes les vidéos de la chaîne Tititechnique avec pagination.
@frontend_bp.route('/acces-videos')
def show_videos():
    """
    Affiche toutes les vidéos de la chaîne Tititechnique avec pagination.

    Cette route récupère toutes les vidéos disponibles dans la base de données et les affiche en utilisant la pagination.
    Le nombre de vidéos par page est défini et la page actuelle est déterminée par les paramètres de la requête.

    :return: Le template HTML 'frontend/videos.html' rendu avec les vidéos paginées, la page actuelle, et le nombre total de pages.

    Description:
        - Récupère toutes les vidéos de la base de données en utilisant la fonction `get_videos_from_db`.
        - Calcule l'index des vidéos à afficher en fonction du numéro de la page demandée et du nombre de vidéos par page.
        - Rend le template 'frontend/videos.html' avec les vidéos de la page actuelle, ainsi que les informations de pagination
          (numéro de page et nombre total de pages).
    """
    # Nombre de vidéos par page.
    per_page = 9
    # Récupération du numéro de page, par défaut 1.
    page = request.args.get('page', 1, type=int)

    # Création d'une instance de YouTubeManager.
    videos = get_videos_from_db()

    # Calcul de l'index des vidéos à afficher.
    start = (page - 1) * per_page
    end = start + per_page

    paginated_videos = videos[start:end]
    # Calcul du nombre total de pages.
    total_pages = (len(videos) + per_page - 1) // per_page

    return render_template('frontend/videos.html', videos=paginated_videos, page=page,total_pages=total_pages)


# Route permettant de récupérer les vidéos populaires.
@frontend_bp.route('/popular_videos')
def show_popular_videos():
    """
    Affiche les vidéos populaires.

    Cette route récupère toutes les vidéos disponibles dans la base de données, puis filtre et affiche celles qui sont
    considérées comme populaires en utilisant une fonction dédiée.

    :return: Le template HTML 'popular_videos.html' rendu avec la liste des vidéos populaires.

    Description:
        - Récupère toutes les vidéos de la base de données en utilisant la fonction `get_videos_from_db`.
        - Filtre ces vidéos pour obtenir uniquement celles considérées comme populaires en utilisant la fonction
          `popular_videos`.
        - Rend le template 'popular_videos.html' avec les vidéos populaires récupérées.
    """
    # Récupération des vidéos de la base de données.
    videos = get_videos_from_db()
    # Récupération des vidéos populaires avec la fonction popular_videos().
    popular = popular_videos(videos)

    return render_template('popular_videos.html', videos=popular)


# Route permettant d'afficher les vidéos archivées.
@frontend_bp.route('video/archives/<month_year>')
def show_archived_videos(month_year):
    """
    Affiche les vidéos archivées pour un mois et une année donnés.

    Cette route récupère les vidéos archivées pour le mois et l'année spécifiés dans l'URL, et les affiche

    :param month_year: Une chaîne de caractères représentant le mois et l'année des vidéos archivées à afficher,
                       au format 'MM-YYYY' (par exemple, '08-2024').

    :return: Le template HTML 'frontend/archived_videos.html' rendu avec les vidéos archivées correspondant au mois
             et à l'année spécifiés, ainsi que les informations de pagination.

    Description:
        - Récupère les vidéos archivées à partir de la base de données en utilisant la fonction `archived_videos`.
        - Filtre les vidéos pour obtenir celles correspondant au mois et à l'année fournis.
    """
    # Nombre de vidéos par page
    per_page = 9
    # Récupération du numéro de page, par défaut 1
    page = request.args.get('page', 1, type=int)

    # Utiliser la méthode archived_videos pour récupérer les vidéos archivées.
    # Récupération de toutes les vidéos.
    videos = get_videos_from_db()
    # Création du dictionnaire des vidéos archivées.
    archived = archived_videos(videos)
    archived = archived.get(month_year, [])

    # Calcul de l'index des vidéos à afficher.
    start = (page - 1) * per_page
    end = start + per_page

    paginated_videos = archived[start:end]

    # Calcul du nombre total de pages.
    total_pages = (len(archived) + per_page - 1) // per_page

    return render_template('frontend/archived_videos.html', month_year=month_year, archived=archived,
                           videos=paginated_videos, page=page, total_pages=total_pages
                           )


# Route permettant de visualiser une vidéo en particulier afin de laisser un commentaire.
@frontend_bp.route('/affichage-video/<int:video_id>', methods=['GET', 'POST'])
def display_video(video_id):
    """
    Route permettant d'accéder à une vidéo particulière du blog.

    Args:
        video_id (int): L'identifiant de la vidéo à afficher.

    Returns:
        Template HTML 'frontend/video.html' avec les détails de la vidéo et ses commentaires associés.

    Raises:
        404 Error: Si aucune vidéo correspondant à l'ID spécifié n'est trouvée dans la base de données.
    """
    # Création de l'instance des formulaires.
    formcommentvideo = CommentVideoForm()

    # Récupération due la vidéo spécifiée par l'id depuis la base de données.
    video = Video.query.get_or_404(video_id)

    # Vérification de l'existence due la vidéo.
    if not video:
        # Si la vidéo n'existe pas, erreur 404 renvoyée.
        abort(404)

    # Récupération des commentaires associés à cette vidéo.
    comment_video = CommentVideo.query.filter_by(video_id=video_id).all()

    return render_template("frontend/video.html", video=video, video_id=video_id,
                           comment_video=comment_video, formcommentvideo=formcommentvideo)
            

templates/frontend/accueil.html
{% extends 'base.html.jinja2' %}

{% block head_content %}
<meta name="description" content="Blog de Tititechnique renseignant sur les techniques de bricolage, jardinage,
    et tout autre chose afin de pouvoir réaliser des petits travaux chez soi en toute sécurité.">
<title>{% block title %}Le Blog de TitiTechnique{% endblock %}</title>

<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.0/gsap.min.js"></script>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
{% endblock %}

<!-- body -->
{% block body_content %}

<!-- main -->
{% block main_content %}
<div class="main-content">
    <div class="space"></div>

    <!-- Conteneur de la bannière -->
    <div class="banniere">
        <img src="{{ url_for('static', filename='Images/images_bannière_logo/banniere_titi.png') }}"
             alt="image de la bannière de titi.">
    </div>

    <div class="space"></div>
    <div class="separation"></div>
    <div class="space"></div>

    <!-- Conteneur titre -->
    <div class="title-container-landing">
        <h1 class="h1-landing">Je vous souhaite la bienvenue sur le blog de TitiTechnique</h1>
    </div>

    <div class="space"></div>
    <div class="separation"></div>
    <div class="space"></div>

    <!-- Conteneur de la section principal -->
    <div class="content-section-landing">
        <!-- Cadre extérieur -->
        <div class="outer-frame">

            <!-- Cadre intérieur -->
            <div class="inner-frame">

                <!-- Section des photos de la page d'accueil -->
                <section class="photo-gallery">

                    <!-- Première photo -->
                    <div class="content-block">
                        <img class="pics-accueil"
                             src="{{ url_for('static', filename='Images/images_accueil/jardin1.png') }}"
                             alt="Image de jardinage">
                        <p class="text-accueil">
                            Si vous voulez tout savoir et plus encore sur le jardinage, je vous
                            donnerai tous les conseils nécessaires.
                        </p>
                    </div>

                    <!-- Deuxième photo -->
                    <div class="content-block">
                        <img class="pics-accueil"
                             src="{{ url_for('static', filename='Images/images_accueil/brico1.png') }}"
                             alt="Image de bricolage">
                        <p class="text-accueil">
                            Je vous propose de vous apprendre à bricoler de manière efficace.
                            Et surtout, sans vous prendre la tête.
                        </p>
                    </div>
                    <!-- Troisième photo -->
                    <div class="content-block">
                        <img class="pics-accueil"
                             src="{{ url_for('static', filename='Images/images_accueil/divers1.png') }}"
                             alt="Image de titi pour videos Youtube">
                        <p class="text-accueil">
                            Depuis ce blog, vous allez avoir accès à toutes les vidéos de ma chaîne <b><a
                                class="surlignage-accueil" href="https://www.youtube.com/@titi.lebricoleur">Youtube</a></b>. Ainsi que la
                            possibilité de poster vos commentaires.
                        </p>
                    </div>

                    <!-- Quatrième photo -->
                    <div class="content-block">
                        <img class="pics-accueil"
                             src="{{ url_for('static', filename='Images/images_accueil/forum1.png') }}"
                             alt="Image de titi pour forum">
                        <p class="text-accueil">
                            Et surtout, nous pourrons échanger tous ensemble dans la section <b><a
                                class="surlignage-accueil" href="{{ url_for('frontend.forum') }}">"Forum"</a></b>. Afin de pouvoir nous parler de
                            manière plus directe et plus sympathiquement surtout.
                        </p>
                    </div>
                </section>

                <div class="separation"></div>
                <div class="space"></div>

                <!-- Photo de bienvenue -->
                <div class="content-block-end">
                    <img class="pics-accueil-fin"
                         src="{{ url_for('static', filename='Images/images_accueil/bienvenue.png') }}"
                         alt="image de bienvenue">
                </div>

                <div class="space"></div>

                <div class="end">
                    <p class="p-ending">
                        Bonne navigation sur le blog.
                    </p>

                    <p class="p-ending">
                        J'espère que vous apprécierez votre visite.
                    </p>
                </div>

                <div class="space"></div>
                <div class="separation"></div>
                <div class="space"></div>

                <!-- Conteneur pour le carrousel -->
                <div class="container-carrousel">
                    <div class="col-lg-8">
                        <!-- Section des nouvelles vidéos -->
                        <section class="new-videos">
                            <!-- Titre de la section -->
                            <h2 class="h2-landing">Nouvelles vidéos</h2>

                            <div class="space2"></div>

                            <div id="carousel-new-videos" class="carousel slide" data-ride="carousel">
                                <div class="carousel-inner">
                                    {% for video in current_month %}
                                    <div class="carousel-item {% if loop.first %}active{% endif %}">
                                        <div class="d-flex">

                                            <!-- Vidéo -->
                                            <div class="video-container">
                                                <iframe width="450" height="215"
                                                        src="https://www.youtube.com/embed/{{ video.video_id }}"
                                                        frameborder="0"
                                                        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                                        allowfullscreen></iframe>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                                <a class="carousel-control-prev" href="#carousel-new-videos" role="button"
                                   data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Précédent</span>
                                </a>
                                <a class="carousel-control-next" href="#carousel-new-videos" role="button"
                                   data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Suivant</span>
                                </a>
                            </div>
                        </section>

                        <div class="space2"></div>
                        <div class="separation"></div>
                        <div class="space2"></div>

                        <!-- Section des vidéos les plus populaires -->
                        <section class="other-videos">
                            <!-- Titre de la section -->
                            <h2 class="h2-landing">Vidéos les plus populaires</h2>

                            <div class="space2"></div>

                            <div id="carousel-popular-videos" class="carousel slide" data-ride="carousel">
                                <div class="carousel-inner">
                                    {% for video in popular %}
                                    <div class="carousel-item {% if loop.first %}active{% endif %}">
                                        <div class="d-flex">
                                            <!-- Vidéo -->
                                            <div class="video-container">
                                                <iframe width="450" height="215"
                                                        src="https://www.youtube.com/embed/{{ video.video_id }}"
                                                        frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope;
                                        picture-in-picture" allowfullscreen></iframe>
                                            </div>
                                            <div class="space"></div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                                <a class="carousel-control-prev" href="#carousel-popular-videos" role="button"
                                   data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Précédent</span>
                                </a>
                                <a class="carousel-control-next" href="#carousel-popular-videos" role="button"
                                   data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Suivant</span>
                                </a>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
        <div class="separation"></div>
    </div>
</div>
{% endblock %}
{% endblock %}

templates/frontend/archived_videos.html
{% extends 'base.html.jinja2' %}

{% block head_content %}
    <meta name="description" content="Vidéos archivées du blog ne correspondant pas au mois courant.">
    <title>{% block title %}Archives des videos{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='CSS/videos.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='CSS/subject_forum.css') }}">
{% endblock %}

    {% block header_content %}
    {% endblock %}

{% block main_content %}
<div class="back">
    <a href="{{ url_for('landing_page') }}">Retour à l'accueil</a>
</div>
<br><br>
<div class="separation"></div>
<h1>Archives des vidéos de TitiTechnique pour {{ month_year }}</h1>
<div class="container-vidéo">
    {% for video in videos %}
    <div class="video-item">
        <h3>{{ video.title }}</h3>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/{{ video.video_id }}"
                frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
        <br>
        <div class="informations">
            <p>Date de publication : {{ video.published_at }}</p>
            <p>Vues : {{ video.view_count }}</p>
            <p>Likes : {{ video.like_count }}</p>
            <p>Commentaires : {{ video.comment_count }}</p>
        </div>
        <br>
        <a href="{{ url_for('frontend.display_video', video_id=video.id) }}">Commenter la vidéo</a>
    </div>
    <br><br>
    {% endfor %}
</div>

<br>
<div class="separation"></div>
<br>

{% endblock %}

templates/frontend/forum.html
{% extends 'base.html.jinja2' %}

{% block head_content %}
<meta name="description" content="Forum du blog permettant de discuter, interagir et donner son avis sur le blog.">
<title>{% block title %}Bienvenue sur le forum du blog{% endblock %}</title>
{% endblock %}

<!-- body -->
{% block body_content %}

<!-- main -->
{% block main_content %}
<div class="main-content">

    <!-- cadre extérieur -->
    <div class="outer-frame">

        <!-- cadre intérieur -->
        <div class="inner-frame">

            <!-- division de retour à la page d'accueil -->
            <div class="space2"></div>
            <div class="back-link-landing">
                <a class="btn-primary" href="{{ url_for('landing_page') }}">Retour à la page d'accueil</a>
            </div>

            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='Images/images_accueil/forum1.png') }}"
                     alt="Titi à la table des discussion"
                     class="avatar-form">
            </div>

            <!-- Conteneur titre -->
            <div class="title-container-landing">
                <h1 class="h1-landing">Forum de discussion</h1>
            </div>

            <div class="space2"></div>
            <div class="separation"></div>
            <div class="space2"></div>

            <!-- Division pour image forum -->
            <div class="forum-image-container">
                <!-- Première photo -->
                <div class="forum-pic">
                    <div class="forum-pic-left">
                        <img src="{{ url_for('static', filename='Images/images_forum/forum4.png') }}"
                             alt="Titi répare son vélo"
                             class="forum-pic-img">
                    </div>
                    <!-- Deuxième photo -->
                    <div class="forum-pic-right">
                        <img src="{{ url_for('static', filename='Images/images_forum/forum5.png') }}"
                             alt="Titi fait de la peinture"
                             class="forum-pic-img">
                    </div>
                </div>
            </div>

            <div class="space-form"></div>

            <!-- Séparation -->
            <hr class="politique-divider">

            <div class="form-container">
                <h3 class="h3-forum">Ajouter un sujet sur le forum</h3>

                <div class="space-form"></div>

                <!-- Conteneur ajout de sujet -->
                <form id="addSubjectForm" method="POST"
                      action="{{ url_for('user.add_subject_forum') }}" class="form-base">

                    <!-- Token CSRF pour la sécurité -->
                    {{ formsubjectforum.csrf_token }}

                    <!-- Champ pour le nouveau sujet -->
                    <div class="form-group">
                        {{ formsubjectforum.nom.label }}
                        {{ formsubjectforum.nom(size=20) }}
                    </div>

                    <!-- bouton de soumission du formulaire -->
                    <button type="submit" class="btn-primary-forum">
                        {{ formsubjectforum.submit.label }}
                    </button>
                </form>
            </div>
            <div class="space2"></div>

            <!-- Conteneur de la liste des sujets -->
            <div class="subjects-container">
                <h3 class="h4-forum">Sujets disponibles</h3>

                <div class="space2"></div>

                <!--tableau des sujets -->
                <table class="subjects-table">
                    <thead>
                    <tr>
                        <th>Sujet</th>
                        <th>Auteur</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for subject in subjects %}
                    <tr>
                        <td data-label="Sujet" class="subject-name">{{ subject.nom }}</td>
                        <td data-label="Auteur" class="subject-author">{{ subject.author }}</td>
                        <td data-label="Action">
                            <a href="{{ url_for('frontend.forum_subject', subject_id=subject.id) }}"
                               class="btn-secondary-forum">Voir</a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% endblock %}

templates/frontend/videos.html
{% extends 'base.html.jinja2' %}

{% block head_content %}
<meta name="description" content="Toutes les vidéos de la chaîne Youtube de TitiTechnique.">
<title>{% block title %}Accès à toutes les vidéos de la chaîne de Titi{% endblock %}</title>
{% endblock %}

<!-- body -->
{% block body_content %}

<!-- main -->
{% block main_content %}
<div class="main-content">

    <!-- cadre extérieur -->
    <div class="outer-frame">

        <!-- cadre intérieur -->
        <div class="inner-frame">

            <!-- division de retour à la page d'accueil -->
            <div class="space2"></div>
            <div class="back-link-landing">
                <a class="btn-primary" href="{{ url_for('landing_page') }}">Retour à la page d'accueil</a>
            </div>
            <div class="space"></div>

            <!-- Conteneur titre -->
            <div class="title-container-landing">
                 <h1 class="h1-landing">Vidéos de TitiTechnique</h1>
            </div>

            <div class="space"></div>
            <div class="separation"></div>
            <div class="space"></div>

    <!-- Conteneur de la section principal -->
    <div class="content-section-landing">
        <!-- cadre extérieur -->
        <div class="outer-frame">

            <!-- cadre intérieur -->
            <div class="inner-frame">

                <!-- Conteneur des vidéos -->
                <div class="video-container">
                    {% for video in videos %}
                    <div class="video-item">
                        <h3 class="h3-video">{{ video.title }}</h3>
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/{{ video.video_id }}"
                                frameborder="0"
                                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                allowfullscreen></iframe>

                        <div class="separation"></div>
                        <div class="space2"></div>

                        <div class="informations">
                            <p>Date de publication : {{ moment(video.published_at).format('DD-MM-YYYY') }}</p>
                            <p>Vues : {{ video.view_count }}</p>
                            <p>Likes : {{ video.like_count }}</p>
                            <p>Commentaires : {{ video.comment_count }}</p>
                        </div>

                        <div class="space2"></div>

                        <a href="{{ url_for('frontend.display_video', video_id=video.id) }}">Commenter la vidéo</a>
                    </div>
                    {% endfor %}
                </div>

                <div class="space"></div>
                <div class="separation"></div>
                <div class="space"></div>

                <!-- Pagination -->
                <div class="pagination">
                    {% if page > 1 %}
                    <a href="{{ url_for('frontend.show_videos', page=page-1) }}" class="prev-next">Précédent</a>
                    {% endif %}

                    <!-- Pages précédentes -->
                    {% for p in range(1, total_pages + 1) %}
                    {% if p <= 2 or p >= total_pages - 1 or (p >= page - 1 and p <= page + 1) %}
                    <a href="{{ url_for('frontend.show_videos', page=p) }}" class="{% if page == p %}active{% endif %}">{{
                        p }}</a>
                    {% elif p == page - 1 or p == page + 1 %}
                    <span class="dots" onclick="showPageSelection()">...</span>
                    {% endif %}
                    {% endfor %}

                    {% if page < total_pages %}
                    <a href="{{ url_for('frontend.show_videos', page=page+1) }}" class="prev-next">Suivant</a>
                    {% endif %}
                </div>

                <!-- Modal pour choisir une page (à afficher si les '...' sont cliqués) -->
                <div id="pageSelectionModal" style="display: none;">
                    <div>
                        <label for="pageSelect">Choisissez une page :</label>
                        <select id="pageSelect">
                            {% for p in range(1, total_pages + 1) %}
                            <option value="{{ p }}" {% if p== page %}selected{% endif %}>Page {{ p }}</option>
                            {% endfor %}
                        </select>
                        <button onclick="navigateToSelectedPage()">OK</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
<script>
  // Affiche la fenêtre de sélection de page
  function showPageSelection() {
    document.getElementById('pageSelectionModal').style.display = 'block';
  }

  // Navigue vers la page sélectionnée dans le modal
  function navigateToSelectedPage() {
    const selectedPage = document.getElementById('pageSelect').value;
    window.location.href = "{{ url_for('frontend.show_videos', page='') }}" + selectedPage;
  }
</script>
{% endblock %}