app/User/__init__.py
"""
Code permettant de définir l'accès aux routes concernant les méthodes utilisateurs du blog.
"""

from flask import Blueprint

user_bp = Blueprint('user', __name__)

from app.User import routes

app/User/routes.py
"""
Code permettant de définir les routes concernant les fonctions des utilisateurs du blog comme l'enregistrement
 et l'accès aux formulaires.
"""
from markupsafe import escape

from flask_login import current_user
from flask import request, render_template, redirect, url_for, flash

from app.User import user_bp

from app.Models import db

from app.Models.subject_forum import SubjectForum
from app.Models.comment_subject import CommentSubject
from app.Models.reply_subject import ReplySubject

from app.Models.videos import Video
from app.Models.comment_video import CommentVideo
from app.Models.reply_video import ReplyVideo

from app.Models.forms import ReplySubjectForm, CommentVideoForm, ReplyVideoForm, NewSubjectForumForm

# Route permettant de créer un sujet pour le forum.
@user_bp.route("/forum/creation-sujet", methods=['GET', 'POST'])
def add_subject_forum():
    """
    Permet à un utilisateur de créer un nouveau sujet sur le forum.
    
    Returns:
        redirect : Redirige vers la page de sujet du forum.
    """
    # Création de l'instance du formuaire pour créer le sujet.
    formsubjectforum = NewSubjectForumForm()
    
    if request.method == "POST":
        nom_sbject_forum = escape(request.form.get("nom"))
        subject_forum = SubjectForum(nom=nom_sbject_forum, author="Utilisateur")
        
    # Enregistrement du sujet dan la base de données.
    db.session.add(subject_forum)
    db.session.commit()
    
    # Fermeture de la base de données.
    db.session.close()
    
    # Récupération de tous les sujets après l'ajout du dernier sujet.
    subjects = SubjectForum.query.all()
    
    return render_template("frontend/forum.html", formsubjectforum=formsubjectforum, subjects=subjects) + "#sujet"
        
    
    
# Route permettant de commenter un sujet du forum.
@user_bp.route("/forum/commentaires-sujet", methods=['POST'])
def comment_subject():
    """
    Permet à un utilisateur de laisser un commentaire sur un sujet du forum.

    Returns :
         redirect : Redirige vers la page du sujet du forum après avoir laissé un commentaire.
    """
    
    # Obtention de l'id du sujet du forum à partir de la requête POST.
    subject_id = request.form.get("subject_id")
    comment_content = request.form.get("comment_content")

    # Vérification que le sujet et le contenu du commentaire existent.
    if not subject_id or not comment_content:
        flash("L'identifiant du sujet ou le contenu du commentaire est manquant.", "error")
        return redirect(url_for("frontend.forum"))  # Redirige vers la page du forum ou une page d'erreur appropriée.

    # Création d'un nouvel objet de commentaire avec les données actuelles.
    new_comment = CommentSubject(comment_content=comment_content, subject_id=subject_id)

    # Ajouter le nouveau commentaire à la base de données.
    db.session.add(new_comment)
    db.session.commit()
    
    # Fermeture de la session.
    db.session.close()

    # Redirection sur la page d'affichage des sujets après ajout du commentaire.
    return redirect(url_for("frontend.forum_subject", subject_id=subject_id))


# Route permettant de répondre à un commentaire.
@user_bp.route("/comment<int:comment_subject_id>/reply_subject", methods=['GET', 'POST'])
def comment_replies_subject(comment_subject_id):
    """
    Permet à un utilisateur de répondre à un commentaire sur un sujet du forum.

    Args :
        comment_subject_id (int) : L'identifiant du commentaire auquel répondre.

    Returns :
        redirect ou render_template : Redirige vers la page du forum après avoir ajouté une réponse,
                                      ou affiche le formulaire de réponse si la méthode est GET.
    """
    # Création de l'instance du formulaire.
    formsubjectreply = ReplySubjectForm()

    # Récupérer le commentaire par son id.
    comment = CommentSubject.query.get(comment_subject_id)

    if not comment:
        flash("Le commentaire n'a pas été trouvé.", "error")
        return redirect(url_for("frontend.forum"))

    if formsubjectreply.validate_on_submit():
        # Obtenir le contenu du commentaire à partir de la requête POST.
        reply_content = formsubjectreply.reply_content.data

        # Obtenir l'ID du commentaire parent à partir du formulaire
        comment_id = formsubjectreply.comment_id.data

        # Créer une nouvelle réponse au commentaire.
        new_reply = ReplySubject(reply_content=reply_content, comment_id=comment_id)

        # Ajouter le nouveau commentaire à la table de données.
        db.session.add(new_reply)
        db.session.commit()
        
        # Récupération des sujets de la base de données.
        subject = SubjectForum.query.get(comment.subject_id)
        
        # Fermeture de la session.
        db.session.close()
        
        
        flash("La réponse au commentaire a bien été enregistrée.", "success")

        # Redirection vers la page du sujet du forum
        return redirect(url_for("frontend.forum_subject", subject_id=comment.subject_id))

    # Si le formulaire n'est pas validé ou en méthode GET, affichez le formulaire de réponse
    return render_template("user/reply_form_subject.html", form=formsubjectreply, comment=comment)


# Route permettant de joindre le formulaire afin de poster une réponse à un commentaire.
@user_bp.route("/comment<int:comment_id>/reply_form_subject", methods=['GET'])
def reply_form_subject(comment_id):
    """
    Affiche le formulaire pour répondre à un commentaire sur un sujet.

    Args:
        comment_id (int) : L'identifiant du commentaire auquel répondre.

    Returns :
        render_template : Le template HTML pour afficher le formulaire de réponse.
    """
    # Création d'une instance du formulaire.
    formsubjectreply = ReplySubjectForm()
    # Récupération des commentaires du sujet.
    comment = db.session.get(CommentSubject, comment_id)

    return render_template("user/reply_form_subject.html", formsubjectreply=formsubjectreply,
                           comment=comment)


# Route permettant de poster un commentaire dans la section vidéo du blog.
@user_bp.route('/commentaires-video', methods=['GET', 'POST'])
def comment_video():
    """
    Permet à un utilisateur de laisser un commentaire sur une vidéo.

    Returns:
        redirect : Redirige vers la page de la vidéo après avoir laissé le commentaire.
    """
    # Création de l'instance du formulaire.
    formcommentvideo = CommentVideoForm()
    
    # Obtention de l'id de la vidéo à partir de la requête POST.
    video_id = request.form.get("video_id")
    comment_content = request.form.get("comment_content")
    

    if request.method == 'POST' and formcommentvideo.validate_on_submit():
        
        # Vérification que le video_id et le contenu du commentaire existent.
        if not video_id or not comment_content:
            flash("L'identifiant de la vidéo ou le contenu du commentaire est manquant.", "error")
            return redirect(url_for("frontend.videos"))

        # Création d'un nouvel objet de commentaire.
        new_comment = CommentVideo(comment_content=comment_content, video_id=video_id)

        # Ajout du nouveau commentaire à la base de données.
        db.session.add(new_comment)
        db.session.commit()
        
        # Fermeture de la base de données.
        db.session.close()

    # Redirection sur la page d'affichage de la vidéo après ajout du commentaire.
    return redirect(url_for("frontend.display_video", video_id=video_id))


# Route permettant de répondre à un commentaire d'une vidéo.
@user_bp.route('/comment_replies_video/<int:comment_video_id>', methods=['GET', 'POST'])
def comment_replies_video(comment_video_id):
    """
    Permet à un utilisateur de répondre à un commentaire d'une vidéo.

    Args :
        comment_video_id (int) : L'identifiant du commentaire auquel répondre.

    Returns :
        redirect ou render_template : Redirige vers la page de la présentation, des vidéos
        après avoir ajouté une réponse, ou affiche le formulaire de réponse si la méthode est GET.
    """
    # Création de l'instance du formulaire.
    formreply = ReplyVideoForm()

    # Récupérer le commentaire par son id.
    comment = CommentVideo.query.get(comment_video_id)

    if not comment:
        flash("Le commentaire n'a pas été trouvé.", "error")
        return redirect(url_for("frontend.show_videos"))

    if formreply.validate_on_submit():

        # Obtenir le contenu du commentaire à partir de la requête POST.
        reply_content = formreply.reply_content.data

        # Obtenir l'ID du commentaire parent à partir du formulaire
        comment_id = formreply.comment_id.data

        # Créer une nouvelle réponse au commentaire.
        new_reply = ReplyVideo(reply_content=reply_content, comment_id=comment_id)

        # Ajouter le nouveau commentaire à la table de données.
        db.session.add(new_reply)
        db.session.commit()
        
        video = Video.query.get(comment.video_id)

        # Fermeture de la session.
        db.session.close()
        
        flash("La réponse au commentaire a bien été enregistrée.", "success")

        # Redirection vers la page du sujet du forum
        return redirect(url_for("frontend.display_video", video_id=comment.video_id))

    # Si le formulaire n'est pas validé ou en méthode GET, affichage du formulaire de réponse.
    return render_template("user/reply_form_video.html", formreply=formreply, comment=comment)


# Route permettant de joindre le formulaire afin de poster une réponse à un commentaire.
@user_bp.route("/comment<int:comment_id>/reply_form_video", methods=['GET'])
def reply_form_video(comment_id):
    """
    Affiche le formulaire pour répondre à un commentaire sur une video.

    Args:
        comment_id (int) : L'identifiant du commentaire auquel répondre.

    Returns :
        render_template : Le template HTML pour afficher le formulaire de réponse.
    """

templates/user/confirm_unsubscribe.html
{% extends 'baseform.html.jinja2' %}

{% block head_content %}
<meta name="description" content="Formulaire de désinscription.">
<title>{% block title %}Formulaire de désinscription afin de ne plus faire parti du blog de <b>Titi Technique</b>{%
    endblock %}</title>
{% endblock %}

{% block body_content %}
<!-- Bordure extérieure -->
<div class="outer-frame">
    <!-- Bordure intérieure -->
    <div class="inner-frame">

        <!-- Introduction des formulaires -->
        <div class="form-intro">
            <p class="title-intro" style="padding:2%;text-indent:0;">
                Confirmation de désinscription
            </p>
            <p class="text-intro">
                Pour supprimer votre compte, veuillez confirmer vos informations de connexion.
            </p>
        </div>

        <!-- Conteneur du formulaire -->
        <form action="{{ url_for('auth.user_unsubscribe') }}" method="POST" class="form-base"
              onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer votre compte ? Cette action est irréversible.');">

            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='/Images/images_formulaires/titi-byebye.png') }}"
                     alt="Image de Titi disant au revoir"
                     class="avatar-form">
            </div>
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            {% if category == 'user_unsubscribe' %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
            {% endwith %}

            <!-- Titre du formulaire -->
            <h3 class="h3-form">Suppression de compte</h3>

            <!-- Token CSRF pour la sécurité -->
            {{ form_unsubscribe.csrf_token }}

            <div class="space-form"></div>

            <!-- Conteneur des champs du formulaire -->
            <div class="form-container">

                <!-- Champ pour le mail -->
                <div class="form-group">
                    {{ form_unsubscribe.email.label }} {{ form_unsubscribe.email() }}
                    {% if form_unsubscribe.email.errors %}
                    <ul>
                        {% for error in form_unsubscribe.email.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <!-- Champ pour le mot de passe -->
                <div class="form-group">
                    {{ form_unsubscribe.label }}
                    {{ form_unsubscribe.password() }}
                    <span class="toggle-password" onclick="togglePassword('password')" aria-controls="password">
                        <i class="fas fa-eye"></i>
                    </span>
                    {% if form_unsubscribe.password.errors %}
                    <ul>
                        {% for error in form_unsubscribe.password.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
                <div class="separation"></div>

                <!-- Champ pour les boutons du formulaire -->
                <div class="container-btn">
                    <button type="submit" class="validated-btn" aria-label="Valider l'inscription">Validation de la
                        souscription
                    </button>
                    <a href="{{ url_for('landing_page') }}" class="cancelled-btn">Annulation et retour à l'accueil</a>
                </div>
            </div>
        </form>
    </div>
</div>


{% endblock %}

templates/user/edit_comment.html
{% extends 'baseform.html.jinja2' %}

{% block head_content %}
    <meta name="description" content="Formulaire de modification d'un commentaire par l'utilisateur.">
    <title>{% block title %}Modification d'un commentaire{% endblock %}</title>
{% endblock %}

{% block header_content %}

{% endblock %}

{% block body_content %}
<div id="introduction">
    <p>Voici le formulaire pour modifier un commentaire.</p>
</div>
<form method="POST" action="{{ url_for('user.change_comment', id=comment.id) }}">
    <div class="imgcontainer">
        <img src="" alt="Avatar" class="avatar">
    </div>
    <h3>Modification du commentaire</h3>
     {{ formchange.hidden_tag() }}
    <div class="container">
        {{ formchange.comment_content.label }} {{ formchange.comment_content() }}
        <input type="hidden" name="subject_id" value="{{ comment.subject_id }}">
        <input type="hidden" name="comment_id" value="{{ comment.id }}">

        <div class="container">
             <button type="submit" class="validatedbtn">Soumettre la réponse</button>
        </div>
    </div>
</form>

{% endblock %}

templates/user/edit_comment_subject.html
{% extends 'baseform.html.jinja2' %}

{% block head_content %}
<meta name="description" content="Formulaire de modification d'un commentaire par l'utilisateur.">
<title>{% block title %}Modification d'un commentaire{% endblock %}</title>
{% endblock %}

{% block header_content %}

{% endblock %}

{% block body_content %}
<!-- Bordure extérieure -->
<div class="outer-frame">

    <!-- Bordure intérieure -->
    <div class="inner-frame">

        <!-- Titre du formulaire -->
        <h2 class="h2-form">Voici le formulaire pour modifier un commentaire.</h2>

        <!-- Conteneur du formulaire -->
        <form method="POST" class="form-base"
              action="{{ url_for('user.change_comment', id=comment.id) }}">

            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='Images/images_formulaires/connexion1.png') }}"
                     alt="Titi à son ordinateur" class="avatar-form">
            </div>

            <!-- Titre de la section du formulaire -->
            <h3 class="h3-form">Modification du commentaire</h3>

            <!-- hidden_tag pour génération du token CSRF pour la sécurité -->
            {{ formchange.hidden_tag() }}

            <div class="space-form"></div>

            <!-- Conteneur de la modification du commentaire -->
            <div class="form-group">
                {{ formchange.comment_content.label }}
                {{ formchange.comment_content(rows=20, cols=20) }}
                <input type="hidden" name="subject_id" value="{{ comment.subject_id }}">
                <input type="hidden" name="comment_id" value="{{ comment.id }}">

                <div class="container-btn">
                    <button type="submit" class="validated-btn"
                            aria-label="Valider la modification">
                        Soumettre la réponse
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/user/edit_comment_video.html
{% extends 'baseform.html.jinja2' %}

{% block head_content %}
<meta name="description" content="Formulaire de modification d'un commentaire par l'utilisateur.">
<title>{% block title %}Modification d'un commentaire{% endblock %}</title>
{% endblock %}

{% block header_content %}

{% endblock %}

{% block body_content %}
<!-- Bordure extérieure -->
<div class="outer-frame">

    <!-- Bordure intérieure -->
    <div class="inner-frame">

        <!-- Titre du formulaire -->
        <h2 class="h2-form">Voici le formulaire pour modifier un commentaire de la section vidéo.</h2>

        <!-- Conteneur du formulaire -->
        <form method="POST" class="form-base"
              action="{{ url_for('user.change_comment_video', id=comment.id) }}">

            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='Images/images_formulaires/connexion1.png') }}"
                     alt="Titi à son ordinateur" class="avatar-form">
            </div>

            <!-- Titre de la section du formulaire -->
            <h3 class="h3-form">Modification du commentaire</h3>

            {{ formchange.hidden_tag() }}

            <div class="space-form"></div>

            <!-- Conteneur de la modification du commentaire -->
            <div class="form-group">
                {{ formchange.comment_content.label }}
                {{ formchange.comment_content(rows=20, cols=20) }}
                <input type="hidden" name="video_id" value="{{ comment.video_id }}">
                <input type="hidden" name="comment_id" value="{{ comment.id }}">

                <!-- Conteneur des boutons du formulaire -->
                <div class="container-btn">
                    <button type="submit" class="validated-btn"
                            aria-label="Valider la modification">
                        Soumettre la réponse
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/user/edit_reply.html
{% extends 'baseform.html.jinja2' %}

{% block head_content %}
    <meta name="description" content="Formulaire de modification d'une réponse à un commentaire par l'utilisateur.">
    <title>{% block title %}Modification d'une réponse à un commentaire{% endblock %}</title>
{% endblock %}

{% block header_content %}

{% endblock %}

{% block body_content %}
<div id="introduction">
    <p>Voici le formulaire pour modifier une réponse à un commentaire.</p>
</div>
<form method="POST" action="{{ url_for('user.change_reply', id=reply.id) }}">
    <div class="imgcontainer">
        <img src="" alt="Avatar" class="avatar">
    </div>
    <h3>Modification de la réponse du commentaire</h3>
     {{ formchangereply.hidden_tag() }}
    <div class="container">
        {{ formchangereply.reply_content.label }} {{ formchangereply.reply_content() }}
        <input type="hidden" name="comment_id" value="{{ reply.subject_id }}">
        <input type="hidden" name="reply_id" value="{{ reply.id }}">

        <div class="container">
             <button type="submit" class="validatedbtn">Soumettre la réponse</button>
        </div>
    </div>
</form>

{% endblock %}

templates/user/edit_reply_subject.html
{% extends 'baseform.html.jinja2' %}

{% block head_content %}
<meta name="description" content="Formulaire de modification d'une réponse à un commentaire par l'utilisateur.">
<title>{% block title %}Modification d'une réponse à un commentaire{% endblock %}</title>
{% endblock %}

{% block header_content %}

{% endblock %}

{% block body_content %}
<!-- Bordure extérieure -->
<div class="outer-frame">

    <!-- Bordure intérieure -->
    <div class="inner-frame">

        <!-- Titre du formulaire -->
        <h2 class="h2-form">Voici le formulaire pour modifier une réponse à un commentaire.</h2>

        <!-- Conteneur du formulaire -->
        <form method="POST" class="form-base"
              action="{{ url_for('user.change_reply', id=reply.id) }}">

            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='Images/images_formulaires/connexion1.png') }}"
                     alt="Titi devant son ordinateur"
                     class="avatar-form">
            </div>

            <!-- Titre de la section du formulaire -->
            <h3 class="h3-form">Modification de la réponse du commentaire</h3>

            <div class="space-form"></div>

            <!-- hidden_tag pour génération du token CSRF pour la sécurité -->
            {{ formchangereply.hidden_tag() }}

            <!-- Conteneur de la modification de la réponse au commentaire -->
            <div class="form-group">
                {{ formchangereply.reply_content.label }}
                {{ formchangereply.reply_content(rows=20, cols=20) }}
                <input type="hidden" name="comment_id" value="{{ reply.subject_id }}">
                <input type="hidden" name="reply_id" value="{{ reply.id }}">

                <!-- Conteneur des boutons du formulaire -->
                <div class="container-btn">
                    <button type="submit" class="validated-btn"
                            aria-label="Valider la modification">
                        Soumettre la réponse
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/user/edit_reply_video.html
{% extends 'baseform.html.jinja2' %}

{% block head_content %}
<meta name="description" content="Formulaire de modification d'une réponse à un commentaire par l'utilisateur.">
<title>{% block title %}Modification d'une réponse à un commentaire{% endblock %}</title>
{% endblock %}

{% block header_content %}

{% endblock %}

{% block body_content %}
<!-- Bordure extérieure -->
<div class="outer-frame">

    <!-- Bordure intérieure -->
    <div class="inner-frame">

        <!-- Titre du formulaire -->
        <h2 class="h2-form">Voici le formulaire pour modifier une réponse à un commentaire d'une vidéo.</h2>

         <!-- Conteneur du formulaire -->
        <form method="POST" class="form-base"
              action="{{ url_for('user.change_reply_video', id=reply.id) }}">

            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='Images/images_formulaires/connexion1.png') }}"
                     alt="Titi devant son ordinateur"
                     class="avatar-form">
            </div>

            <!-- Titre de la section du formulaire -->
            <h3 class="h3-form">Modification de la réponse du commentaire</h3>

            <!-- hidden_tag pour génération du token CSRF pour la sécurité -->
            {{ formchangereply.hidden_tag() }}

            <!-- Conteneur de la modification de la réponse au commentaire -->
            <div class="form-group">
                {{ formchangereply.reply_content.label }}
                {{ formchangereply.reply_content(rows=20, cols=20) }}
                <input type="hidden" name="comment_id" value="{{ reply.video_id }}">
                <input type="hidden" name="reply_id" value="{{ reply.id }}">

                <!-- Conteneur des boutons du formulaire -->
                <div class="container-btn">
                    <button type="submit" class="validated-btn"
                            aria-label="Valider la modification">
                        Soumettre la réponse
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/user/reply_form_subject.html
{% extends 'baseform.html.jinja2' %}

{% block head_content %}
<meta name="description" content="Formulaire de réponse par un utilisateur au sujet posté sur le forum du blog.">
<title>{% block title %}Réponse au sujet du forum du blog{% endblock %}</title>
{% endblock %}

{% block header_content %}

{% endblock %}

{% block body_content %}
<!-- Bordure extérieure -->
<div class="outer-frame">

    <!-- Bordure intérieure -->
    <div class="inner-frame">

        <!-- Titre du formulaire -->
        <h2 class="h2-form">Voici le formulaire pour écrire une réponse aux sujets postés sur le forum. </h2>

        <!-- Conteneur du formulaire -->
        <form method="POST" class="form-base"
              action="{{ url_for('user.comment_replies_subject', comment_subject_id=comment.id, user_pseudo=current_user.pseudo) }}">

            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='Images/images_formulaires/connexion1.png') }}"
                     alt="Titi à son ordinateur" class="avatar-form">
            </div>

            <!-- Titre de la section du formulaire -->
            <h3 class="h3-form">Réponse au commentaire</h3>

            <!-- hidden_tag pour génération du token CSRF pour la sécurité -->
            {{ formsubjectreply.csrf_token }}

            <div class="space-form"></div>

            <!-- Conteneur de la réponse au commentaire -->
            <div class="form-group">
                {{ formsubjectreply.reply_content.label }}
                {{ formsubjectreply.reply_content(rows=20, cols=20) }}
                <input type="hidden" name="subject_id" value="{{ comment.subject_id }}">
                <input type="hidden" name="comment_id" value="{{ comment.id }}">

                <!-- Conteneur des boutons du formulaire -->
                <div class="container-btn">
                    <button type="submit" class="validated-btn" aria-label="Valider la réponse">Soumettre la réponse
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/user/reply_form_video.html
{% extends 'baseform.html.jinja2' %}

{% block head_content %}
<meta name="description" content="Formulaire de réponse par un utilisateur au sujet posté sur le forum du blog.">
<title>{% block title %}Réponse à un commentaire d'un vidéo{% endblock %}</title>
{% endblock %}

{% block header_content %}

{% endblock %}

{% block body_content %}
<!-- Bordure extérieure -->
<div class="outer-frame">

    <!-- Bordure intérieure -->
    <div class="inner-frame">

        <!-- Titre du formulaire -->
        <h2 class="h2-form">Voici le formulaire pour écrire une réponse aux commentaires des vidéos du blog.</h2>

        <!-- Conteneur du formulaire -->
        <form method="POST" class="form-base"
              action="{{ url_for('user.comment_replies_video', comment_video_id=comment.id, user_pseudo=current_user.pseudo) }}">

            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='Images/images_formulaires/connexion1.png') }}"
                     alt="Titi à son ordinateur" class="avatar-form">
            </div>

            <!-- Titre de la section du formulaire -->
            <h3 class="h3-form">Réponse au commentaire</h3>

            <!-- hidden_tag pour génération du token CSRF pour la sécurité -->
            {{ formreply.csrf_token }}

            <div class="space-form"></div>

            <!-- Conteneur de la réponse au commentaire -->
            <div class="form-group">
                {{ formreply.reply_content.label }}
                {{ formreply.reply_content(rows=20, cols=20) }}
                <input type="hidden" name="video_id" value="{{ comment.video_id }}">
                <input type="hidden" name="comment_id" value="{{ comment.id }}">

                <!-- Conteneur des boutons du formulaire -->
                <div class="container-btn">
                    <button type="submit" class="validated-btn" aria-label="Valider la réponse">Soumettre la réponse
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/user/user_form_visio.html
{% extends 'baseform.html.jinja2' %}

{% block head_content %}
<meta name="description" content="Formulaire de demande de visio par l'utilisateur.">
<title>{% block title %}Demande de visio avec Tititechnique{% endblock %}</title>
{% endblock %}

{% block header_content %}

{% endblock %}

{% block body_content %}
<!-- Bordure extérieure -->
<div class="outer-frame">

    <!-- Bordure intérieure -->
    <div class="inner-frame">

        <!-- Titre du formulaire -->
        <h2 class="h2-form">Voici le formulaire afin de demander une visio avec Tititechnique. </h2>

        <!-- Conteneur du formulaire -->
        <form method="POST" action="{{ url_for('chat.send_visio') }}"
            class="form-base" enctype="multipart/form-data">
              

            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='Images/images_formulaires/connexion1.png') }}"
                     alt="Titi à son ordinateur" class="avatar-form">
            </div>

            <!-- Titre de la section du formulaire -->
            <h3 class="h3-form">Demande de visio</h3>

            <!-- hidden_tag pour génération du token CSRF pour la sécurité -->
            {{ formvisio.csrf_token }}

            <div class="space-form"></div>

            <!-- Conteneur des champs du formulaire -->
            <div class="form-container">

                <!-- Conteneur de l'email de l'utilisateur-->
                <div class="form-group">
                    {{ formvisio.label }}
                    {{ formvisio.email }}
                </div>
            </div>

            <!-- Conteneur des boutons du formulaire -->
            <div class="container-btn">
                <button type="submit" class="validated-btn" aria-label="Valider la réponse">
                    Demander la visio
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}